# **03 - Submission**
Memuat model final, memprediksi `test.csv`, dan membuat `submission.csv` sesuai format `sample_submission.csv`.

In [1]:
import warnings
warnings.filterwarnings("ignore")

import sys, os, pickle
sys.path.append("..")

import pandas as pd
from scripts.predict import make_submission

# **1. Read Dataset & Model**

In [2]:
test = pd.read_csv("../data/test.csv")
sample = pd.read_csv("../data/sample_submission.csv")
with open("../models/pipeline_lgbm_structural_damage.pkl", "rb") as f:
    model = pickle.load(f)
print(test.shape, sample.shape)
sample.head()

(228629, 16) (228629, 2)

    building_id damage_grade
0  122207000141      Grade 3
1  284909000871      Grade 1
2  241904000231      Grade 5
3  248308000891      Grade 4
4  300405002981      Grade 2

# **2. Predict & Build Submission**

In [3]:
submission = make_submission(model, test, sample, numeric=True)  # angka 1-5 (evaluator Kaggle gagal membaca teks "Grade 3")
submission.head()

    building_id  damage_grade
0  122207000141             2
1  284909000871             5
2  241904000231             3
3  248308000891             3
4  300405002981             5

# **3. Validasi Format**

In [4]:
assert list(submission.columns) == list(sample.columns)
assert len(submission) == len(sample)
assert (submission["building_id"].values == sample["building_id"].values).all()
assert set(submission["damage_grade"]) <= {1, 2, 3, 4, 5}
print("Format submission valid")
submission["damage_grade"].value_counts(normalize=True).sort_index().round(3)

Format submission valid

damage_grade
1    0.117
2    0.095
3    0.168
4    0.234
5    0.386
Name: proportion, dtype: float64

# **4. Simpan**

In [5]:
os.makedirs("../submissions", exist_ok=True)
submission.to_csv("../submissions/submission.csv", index=False)
print("Tersimpan: ../submissions/submission.csv")

Tersimpan: ../submissions/submission.csv